mongo:
  host: 127.0.0.1
  port: 27017
  database: api-game
  password:
  username:
  authenticationDatabase:
  connectionPerHost: 5

ais.mq:
  host: localhost # connection host
  port: 5672 # 5772 # connection port
  username: guest
  password: guest
  concurrency: 10
  maxConcurrency: 10
  virtualHost: /api-game-2

redis:
  host: localhost
  port: 6379
  password:
  database: 3
  max-active: 10
  max-wait: -1
  max-idle: 8
  timeout: 0
  connectionPoolSize: 200

app:
  name: game-api
  error-log:
    collection: exception_log
    expireDay: 180
  log:
    isUse: true
    filePath: E:\\ittx\\game-api\\log\\
    prefix: game-api
    maxFileSize: 65536

login:
  maxStillState: 300000 # ms
  maxReuse: 1

web:
  accessInterval: 10000 # ms
  isLoose: false

datasources:
  statu: 1
  instants:
    instant-1:
      url: jdbc:mysql://localhost:3306/users?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useOldAliasMetadataBehavior=true
      username: root
      password: 123
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5
      maxActive: 100
      maxIdle: 10
      minIdle: 5
      type: com.alibaba.druid.pool.DruidDataSource
      isDefault: true


spring:
  main:
    allow-bean-definition-overriding: true

## 放开Actuator Web REST 端点,否则访问不到
#management:
#  endpoints:
#    enabled: true
#    web:
#      base-path: /actuator  # 访问根路径
#      exposure:
#        include: "*"