
server.port: 30001

mongo:
  host: 127.0.0.1
  port: 27017
  database: api-game
  password:
  username:
  authenticationDatabase:
  connectionPerHost: 5

ais.mq:
  host: localhost # connection host
  port: 5672 # 5772 # connection port
  username: guest
  password: guest
  concurrency: 10
  maxConcurrency: 10
  virtualHost: /api-game

redis:
  host: localhost
  port: 6379
  password:
  database: 3
  max-active: 10
  max-wait: -1
  max-idle: 8
  timeout: 0
  connectionPoolSize: 200

app:
  name: game-api
  error-log:
    collection: exception_log
    expireDay: 180
  log:
    isUse: true
    filePath: E:\\java\\game-api\\src\\main\\resources\\log\\
    prefix: game-api
    maxFileSize: 65536

login:
  maxStillState: 300000 # ms
  maxReuse: 1

web:
    accessInterval: 10000 # ms
    isLoose: false
