mongo:
  host: 127.0.0.1
  port: 27017
  database: api-game
  password:
  username:
  authenticationDatabase:
  connectionPerHost: 5

app:
  name: game-api
  error-log:
    collection: exception_log
    expireDay: 180
