mongo:
  host: 127.0.0.1
  port: 27017
  database: api-game
  password:
  username:
  authenticationDatabase:
  connectionPerHost: 5

ais.mq:
  host: localhost # connection host
  port: 5672 # 5772 # connection port
  username: guest
  password: guest
  concurrency: 10
  maxConcurrency: 10
  virtualHost: /api-game

app:
  name: game-api
  error-log:
    collection: exception_log
    expireDay: 180
  log:
    isUse: true
    filePath: ./log/

redis:
  host: localhost
  port: 6379
  password:
  database: 4
  max-active: 200
  max-wait: -1
  max-idle: 8
  timeout: 0
  connectionPoolSize: 400

login:
  maxStillState: 300000 # ms
  maxReuse: 1

web:
    accessInterval: 10000 # ms
    isLoose: true